
import {
  Image,
  Heading,
  Copy,
  Minimize2,
  Search,
  Key,
  TrendingUp,
  FolderTree,
  Bot,
  Wrench,
  Link2,
  Eye,
  Sparkles,
  BarChart3,
  Target,
  Layers,
  Globe,
  LinkIcon
} from 'lucide-react'


export type Tool = {
  id?: string
  title: string
  description: string
  href: string
  icon: React.ElementType
  color: string
  lightColor?: string
  category?: string
}

export const tools: Tool[] = [
  {
    title: 'Renombrador de imágenes',
    description: 'Renombra imágenes automáticamente con keywords SEO...',
    href: '/renombrador-images',
    icon: Image,
    color: 'from-sky-500 to-blue-500',
    lightColor: 'from-sky-50 to-blue-100',
    category: 'Optimización',
  },
  {
    title: 'Compresor de imágenes',
    description: 'Reduce el peso de tus imágenes sin perder calidad...',
    href: '/compresor-imagenes',
    icon: Minimize2,
    color: 'from-cyan-500 to-sky-500',
    lightColor: 'from-cyan-50 to-sky-100',
    category: 'Optimización',
  },
  {
    title: 'Generador SEO',
    description: 'Genera títulos y descripciones optimizados con IA...',
    href: '/generar-titulo-seo',
    icon: Heading,
    color: 'from-fuchsia-500 to-pink-500',
    lightColor: 'from-fuchsia-50 to-pink-100',
    category: 'Contenido',
  },
  {
    title: 'Optimizador de contenido',
    description: 'Analiza textos ya publicados y sugiere mejoras...',
    href: '/optimizador-contenido',
    icon: Wrench,
    color: 'from-pink-500 to-purple-500',
    lightColor: 'from-pink-50 to-purple-100',
    category: 'Contenido',
  },
  {
    title: 'Detector de duplicados',
    description: 'Detecta contenido duplicado en la web...',
    href: '/detector-contenido-duplicado',
    icon: Copy,
    color: 'from-violet-500 to-indigo-600',
    lightColor: 'from-violet-50 to-indigo-100',
    category: 'Análisis',
  },
  {
    title: 'Auditor SEO',
    description: 'Analiza tu web y detecta errores técnicos...',
    href: '/seo-audit-tool',
    icon: Search,
    color: 'from-indigo-500 to-slate-600',
    lightColor: 'from-indigo-50 to-slate-100',
    category: 'Análisis',
  },
  {
    title: 'Verificador de enlaces rotos',
    description: 'Revisa tu web y encuentra enlaces que no funcionan...',
    href: '/verificador-enlaces',
    icon: Link2,
    color: 'from-purple-500 to-rose-600',
    lightColor: 'from-purple-50 to-rose-100',
    category: 'Análisis',
  },
  {
    title: 'Validador de Core Web Vitals',
    description: 'Mide velocidad, estabilidad y accesibilidad...',
    href: '/vitals-checker-tool',
    icon: TrendingUp,
    color: 'from-amber-500 to-yellow-500',
    lightColor: 'from-amber-50 to-yellow-100',
    category: 'Rendimiento',
  },
  {
    title: 'Generador de Sitemap',
    description: 'Crea un sitemap.xml al instante...',
    href: '/generador-sitemap',
    icon: FolderTree,
    color: 'from-gray-600 to-stone-500',
    lightColor: 'from-gray-50 to-stone-100',
    category: 'Técnico',
  },
  {
    title: 'Generador de Robots.txt',
    description: 'Detecta si tu sitio ya tiene un robots.txt...',
    href: '/generador-robots',
    icon: Bot,
    color: 'from-stone-500 to-neutral-500',
    lightColor: 'from-stone-50 to-neutral-100',
    category: 'Técnico',
  },
  {
    title: 'Scraper de palabras clave',
    description: 'Extrae keywords de páginas de competidores...',
    href: '/keyword-scraper-tool',
    icon: Key,
    color: 'from-emerald-500 to-lime-500',
    lightColor: 'from-emerald-50 to-lime-100',
    category: 'Investigación',
  },
  {
    title: 'Analizador de competencia',
    description: 'Espía las estrategias SEO de tus rivales...',
    href: '/analizador-competencia',
    icon: Eye,
    color: 'from-teal-500 to-emerald-500',
    lightColor: 'from-teal-50 to-emerald-100',
    category: 'Investigación',
  },
  {
    title: 'Descubrimiento de Keywords',
    description: 'Descubre palabras clave relacionadas con IA avanzada...',
    href: '/keyword-research-discover',
    icon: Sparkles,
    color: 'from-blue-500 to-cyan-500',
    lightColor: 'from-blue-50 to-cyan-100',
    category: 'Investigación',
  },
  {
    title: 'Dificultad de Keywords',
    description: 'Analiza la competencia y dificultad de posicionamiento...',
    href: '/keyword-difficulty',
    icon: Target,
    color: 'from-orange-500 to-red-500',
    lightColor: 'from-orange-50 to-red-100',
    category: 'Investigación',
  },
  {
    title: 'Tendencias de Keywords',
    description: 'Descubre keywords en tendencia y volumen de búsqueda...',
    href: '/keyword-trends',
    icon: TrendingUp,
    color: 'from-green-500 to-emerald-500',
    lightColor: 'from-green-50 to-emerald-100',
    category: 'Investigación',
  },
  {
    title: 'Agrupación de Keywords',
    description: 'Agrupa keywords por intención y similitud semántica...',
    href: '/keyword-clustering',
    icon: Layers,
    color: 'from-purple-500 to-pink-500',
    lightColor: 'from-purple-50 to-pink-100',
    category: 'Investigación',
  },
  {
    title: 'Análisis SERP',
    description: 'Analiza los resultados de búsqueda de Google en profundidad...',
    href: '/serp-analyzer',
    icon: Globe,
    color: 'from-indigo-500 to-purple-500',
    lightColor: 'from-indigo-50 to-purple-100',
    category: 'Análisis',
  },
  {
    title: 'Verificador de Backlinks',
    description: 'Analiza el perfil de enlaces entrantes de cualquier sitio...',
    href: '/backlink-checker',
    icon: LinkIcon,
    color: 'from-rose-500 to-pink-500',
    lightColor: 'from-rose-50 to-pink-100',
    category: 'Análisis',
  },
]